### ISSUE TITLE
Clear logging of cv2

### ISSUE THREAD

**Issue by Aristarhys** [ChaikaBogdan/opencv_webstreamer#1]
`VIDEOIO ERROR: V4L: index 2 is not correct!` must be `stderr` input, but `stderr` redirection to `/dev/null` does not seems to work.

**Comment by ChaikaBogdan** [comment]
Write steps how to get this kind error.

**Comment by Aristarhys** [comment]
Call it with arguments `--device=2`

**Comment by ChaikaBogdan** [comment]
Cannot repeat
C:/GIT/opencv_webstreamer/main.py --frame-size 320 200 --device 2
2018-03-18 11:16:50 MainThread [INFO] - Frame size set to 320x200
2018-03-18 11:16:53 MainThread [ERROR] - Device 2 unavailable or busy
2018-03-18 11:16:53 MainThread [ERROR] - Device 2 unavailable or busy

**Comment by ChaikaBogdan** [comment]
https://stackoverflow.com/questions/1956142/how-to-redirect-stderr-in-python

**Comment by ChaikaBogdan** [comment]
https://stackoverflow.com/questions/43919314/do-not-display-python-opencv-error
