### ISSUE TITLE
Query and set max possible webcam resolution 

### ISSUE THREAD

**Issue by Aristarhys** [ChaikaBogdan/opencv_webstreamer#2]
https://stackoverflow.com/questions/31076403/updating-code-from-opencv-to-opencv2
https://stackoverflow.com/questions/18458422/query-maximum-webcam-resolution-in-opencv

**Comment by ChaikaBogdan** [comment]
https://stackoverflow.com/questions/18458422/query-maximum-webcam-resolution-in-opencv
